src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pushes.urls', namespace='pushes')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/pushes/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from pushes.views import PushesCreateView, UpdateUser, HomeView, UserLoginView, \
    OptionsCreateView, OptionsUpdateView, OptionsDeleteView

app_name = 'pushes'

urlpatterns = [
    path('', HomeView.as_view(), name='home_page'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('update_user/<int:id>', UpdateUser.as_view(), name='update_user'),
    path('create_pushes/', PushesCreateView.as_view(), name='create_pushes'),
    path('option_create/', OptionsCreateView.as_view(), name='options_create'),
    path('option_update/<int:id>', OptionsUpdateView.as_view(), name='options_update'),
    path('option_delete/<int:id>', OptionsDeleteView.as_view(), name='options_delete')

]

src/pushes/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from .managers import CustomUserManager


# Create your models here.


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    image = models.URLField()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['last_name', 'first_name', 'image']
    objects = CustomUserManager()

    def __str__(self):
        return self.email


class Options(models.Model):
    name = models.CharField(max_length=30)
    value = models.BooleanField()

    class Meta:
        db_table = 'options'

    def __str__(self):
        return self.name


class Pushes(models.Model):
    title = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    text = models.TextField()
    image = models.ImageField(upload_to='images/')
    create_date = models.DateTimeField(auto_now_add=True)
    sent_date = models.DateTimeField()
    sent_status = models.BooleanField(default=False)
    sent_count = models.IntegerField(null=True, blank=True)

    class Meta:
        db_table = 'pushes'

    def __str__(self):
        return self.title

src/pushes/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from .models import Pushes, CustomUser, Options


class OptionsForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Укажите имя', 'class': 'form-control'}))
    value = forms.BooleanField(required=False,
                               widget=forms.CheckboxInput(attrs={'class': 'custom-control-checkbox'}))

    class Meta:
        model = Options
        fields = ('name', 'value')


class PushesForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'id'  : 'push-title', 'placeholder': 'Укажите заголовок'}))
    text = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Укажите заголовок'}))
    image = forms.ImageField(
        widget=forms.FileInput(attrs={'placeholder': 'Пример: http://yourapp.com/image.png', 'id': 'image-push', }))
    sent_date = forms.DateTimeField(widget=forms.DateInput(attrs={'placeholder': 'DD/MM/YY'}))
    name = forms.CharField(widget=forms.TextInput(attrs={'id': 'push-name'}))

    class Meta:
        model = Pushes
        fields = ('title', 'text', 'image', 'sent_date', 'name')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class CustomUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'image', 'last_name', 'first_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class MyForm(AuthenticationForm):
    remember_me = forms.BooleanField(required=False,
                                     widget=forms.CheckboxInput(attrs={'class': 'custom-control-checkbox'}))

src/pushes/views.py
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView, ListView

from pushes.forms import CustomUserForm, PushesForm, MyForm, OptionsForm
from pushes.models import CustomUser, Options, Pushes

# Create your views here.

class HomeView(ListView):
    model = Pushes
    template_name = 'adminlte/index.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.order_by('-create_date')


class UpdateUser(UpdateView):
    form_class = CustomUserForm
    template_name = 'registration/update_user.html'
    success_url = '/'

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(CustomUser, id=id_)


class PushesCreateView(SuccessMessageMixin, CreateView):
    form_class = PushesForm
    template_name = 'adminlte/pages/edit.html'
    success_message = 'Pushes successfully create'

    def get_success_url(self):
        return '/'


class UserLoginView(LoginView):
    template_name = 'registration/login.html'
    form_class = MyForm

    def form_valid(self, form):
        remember_me = form.cleaned_data['remember_me']
        if not remember_me:
            self.request.session.set_expiry(0)
            self.request.session.modified = True
        return super().form_valid(form)


class OptionsCreateView(CreateView):
    form_class = OptionsForm
    template_name = 'options_page/create_options.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_options'] = Options.objects.all()
        return context

    def get_success_url(self):
        return '/option_create'


class OptionsUpdateView(UpdateView):
    form_class = OptionsForm
    template_name = 'options_page/update_options.html'

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Options, id=id_)

    def get_success_url(self):
        return '/option_create'


class OptionsDeleteView(DeleteView):
    template_name = 'options_page/delete_options.html'

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(Options, id=id_)

    def get_success_url(self):
        return '/option_create'

src/templates/adminlte/index.html
{% extends 'adminlte/base.html' %}
{% include 'adminlte/lib/_main_header.html' %}
{% load static %}
{% block stylesheets %}
{% include 'adminlte/lib/_styles.html' %}
<link rel="stylesheet" type="text/css" href=" {% static "css/style.css" %}"><link >
{% endblock %}
{% block title %}{% endblock %}
{% block content %}
{% if request.user.is_authenticated == False %}

		<h1>Вы не авторизованы</h1><h3><a href="{% url "pushes:login" %}">Войти</a></h3>
{% endif %}
{% endblock %}

        {# Site JS #}

{% block javascript %}
{% include 'adminlte/lib/_scripts.html' %}
  <script type="application/javascript" src="{% static 'js/js.js' %}"></script>
{% endblock %}

src/templates/adminlte/lib/_main_footer.html
<footer class="main-footer">
	<div class="pull-right hidden-xs">
        {% block footer_right %}
		<b>Version</b> {% block version %}0.1{% endblock %}
        {% endblock %}
	</div>
    {% block footer_left %}
    {% block legal %}
	<strong>Copyright &copy; {% now "Y" %}{% if not site %}.{% endif %}
        {% if site %}
		<a href="http://{{ site.domain }}">{{ site.name }}</a>
        {% endif %}
	</strong> All rights
    reserved.
    {% endblock %}
    {% endblock %}
</footer>

src/templates/adminlte/lib/_main_header.html
{% extends 'adminlte/lib/_main_header.html' %}
{% block logo %}
    <a href="{% block logo_href %}/{% endblock %}" class="logo"><span class="logo-mini"><b>CP</b></span><span class="logo-lg"><b>Control</b>Panel</span></a>
{% endblock %}

{% block nav_custom_menu %}
    <div class="navbar-custom-menu"><ul class="nav navbar-nav">
            {% block header_dropdowns %}
                {% if request.user.is_authenticated %}
                    <li class="dropdown user user-menu"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="{{ request.user.image }}"style="height: 30px; object-fit: cover; width: 30px"class="user-image" alt="User Image"><span class="hidden-xs">{% firstof request.user.get_short_name request.user.get_username %}</span></a><ul class="dropdown-menu">
                            {% block user_header %}
                                <li class="user-header"><img src="{{ request.user.image }}" style="object-fit: cover" class="img-circle" alt="User Image"><p>
                                        Email - {{  request.user.email }}
                                        <small>Member since {{ request.user.date_joined }}</small></p></li>
                            {% endblock %}

                            {% block menu_footer %}
                                <li class="user-footer"><div class="pull-left"><a href="
                                                {% block change_password_url %}{% url 'pushes:update_user' request.user.id %}{% endblock %}"
                                           class="btn btn-default btn-flat">Settings Users</a></div><div class="pull-right"><a href="{% block logout_url %}{% url 'pushes:logout' %}{% endblock %}"
                                           class="btn btn-default btn-flat">Sign
                                            out</a></div></li>
                            {% endblock %}
                        </ul></li>
                {% endif %}
            {% endblock header_dropdowns %}
        </ul></div>
{% endblock nav_custom_menu %}

src/templates/adminlte/lib/_main_sidebar.html
{% extends 'adminlte/lib/_main_sidebar.html' %}

{% block user_panel %}
    {% if request.user.is_authenticated %}

<div class="user-panel">
	<div class="pull-left image">
		<img src="{{ request.user.image }}" style="width: 50px; object-fit:cover;height: 50px"
                     class="img-circle"
                     alt="User Image">
		</div>
		<div class="pull-left info">
			<p>{{ request.user.last_name }} {{ request.user.first_name }}</p>
			<p>
				<i style="color: green" class="fa fa-circle"></i> &nbsp; Online
			</p>
		</div>
	</div>
    {% endif %}

{% endblock %}

{% block nav_links %}
    {% if request.user.is_authenticated %}

	<li style="margin-top: 10%">
		<a href="{% url 'pushes:create_pushes' %}">
			<i class="fa fa-edit fa-2x" style="color: white"></i>
			<span class="text-nav-links">Pushes</span>
		</a>
	</li>
	<li style="margin-top: 10%">
		<a href="{% url 'pushes:options_create' %}">
			<i class="fa fa-cog fa-2x" style="color: white"></i>
			<span class="text-nav-links">Options</span>
		</a>
	</li>
    {% endif %}
{% endblock nav_links %}

src/templates/adminlte/pages/edit.html
{% extends 'adminlte/index.html' %} {% load static %}
<link rel="stylesheet" type="text/css" href=" {% static " css/style.css " %}"> {% block content %}
<div class="box">
    <div style="margin-left: 3%">
        <h3><b>Пуш уведомление</b></h3></div>

    <div class="row">
        <div class="col-sm-5">
            <div class="card">

                <div class="card-body">

                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="box-body" style="margin-left: 5%">
                            <div class="form-group">
                                <label for="title">Заголовок уведомления</label>
                                <label style="float: right">0/50</label>
                                {{ form.title }}
                            </div>
                            <div class="form-group">
                                <label for="title">Текст уведомления</label>
                                {{ form.text }}
                            </div>
                            <div class="form-group">
                                <label for="title">Изображение уведомления</label>
                                {{ form.image }}
                            </div>

                            <div class="form-group">
                                <label for="title">Дата отправки</label>
                                {{ form.sent_date }}
                            </div>

                            <div class="form-group">
                                <label for="title">Название уведомления</label>
                                {{ form.name }} {{ error }}
                            </div>
                            {% if form.errors %}
                            <!-- Error messaging -->
                            <div id="errors">
                                <div class="inner">
                                    <p>There were some errors in the information you entered. Please correct the following:</p>
                                    {{ form.non_field_errors }}
                                    <ul>
                                        {% for field in form %} {% if field.errors %}
                                        <li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %} {% endfor %}
                                    </ul>
                                </div>
                            </div>
                            <!-- /Error messaging -->
                            {% endif %}

                        </div>
                        <button style="margin-left: 7%" type="submit" class="btn btn-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card">
                <h4 style="margin-top: 5%">Предосмотр устройства</h4>
                <h3 align="center" style="margin-top: 10%"><b>Android</b></h3>
                <div class="box-body" style=" height: 210px;    margin-left: auto;
    margin-right: auto;
    width: 29em; background: url(../../../static/images/android_pushes1.png) no-repeat">
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="card">
                                <div class="text-push">
                                </div>
                                <div class="name-push">
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="card">
                                <div id="text-images">
                                    <img class="blah" src="#" id = 'image-android' style=" height:50px; width:50px;object-fit: unset; margin-top: 45%;margin-left: 25%" alt="" />
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
                <h3 align="center"><b>iOS</b></h3>
                <div class="box-body" style=" height: 500px;width: 32em; margin-right: auto; margin-left: auto; background: url(../../../static/images/ios_pushes1.png) no-repeat">
                    <div class="row">
                        <div class="col-sm-8">
                            <div class="card">
                                <div class="text-push" style="margin-left: 20%; margin-top: 17%">
                                </div>
                                <div class="name-push" style="margin-left: 20%">
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="card">
                                <div id="text-images">
                                    <img class=" blah" id = 'image-ios' src="#" height="50px" width="50px" style="object-fit: unset; margin-top: 35%;margin-left: 25%" alt="" />
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<!-- form start -->
<!-- /.box -->
{% endblock %}
{% block body_tail %}
{% endblock %}

src/templates/options_page/create_options.html
{% extends 'adminlte/index.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href=" {% static "css/style.css" %}">
{% block content %}
<div class="box" style="padding: 10px">
   <div style="margin-left: 3%">
      <h3><b>Создание Options</b></h3>
   </div>
   <div class="row">
      <div class="col-sm-5">
         <div class="card">
            <div class="card-body">
               <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="box-body" style="margin-left: 5%">
                     <div class="form-group">
                        <label for="title">Название Options</label>
                        {{ form.name }}
                     </div>
                     <div class="form-group">
                        <label for="title">Значение Options</label>
                        <span style="margin-left: 1%">{{ form.value }}</span>
                     </div>
                     {% if form.errors %}
                     <!-- Error messaging -->
                     <div id="errors">
                        <div class="inner">
                           <p>There were some errors in the information you entered. Please correct the following:</p>
                           {{ form.non_field_errors }}
                           <ul>
                              {% for field in form %}
                              {% if field.errors %}
                              <li>{{ field.label }}: {{ field.errors|striptags }}</li>
                              {% endif %}
                              {% endfor %}
                           </ul>
                        </div>
                     </div>
                     <!-- /Error messaging -->
                     {% endif %}
                  </div>
                  <button style="margin-left: 7%" type="submit" class="btn btn-primary">Создать</button>
               </form>
            </div>
         </div>
      </div>
   </div>
</div>
<div>
{% if all_options %}
   <h2>Список всех Options</h2>
{% endif %}
   {% for i in all_options %}
   <p>
   <h4><a href="{% url 'pushes:options_update' i.id %}">{{ i.name }}</a></h4>
   </p>
   {% endfor %}
</div>
<!-- /.box -->
{% endblock %}
{% block body_tail %}
{% endblock %}

src/templates/options_page/delete_options.html
{% extends 'adminlte/base.html' %}
{% include 'adminlte/lib/_main_header.html' %}
{% load static %}
{% block stylesheets %}
{% include 'adminlte/lib/_styles.html' %}
<link rel="stylesheet" type="text/css" href=" {% static " css/style.css " %}">
<link>
{% endblock %} {% block title %}{% endblock %} {% block content %}
<hr>
<h3>
   <a> Вы действительно хотите удалить?</a>
</h3>
<form method="POST" action="">
   {% csrf_token %}
   <button type="submit" style="width: 7%" class="btn btn-danger">Удалить</button>
   <a href="{% url 'pushes:options_update' object.id %}">
   <input type="" style="width: 7%" class="btn btn-warning" value="Отмена">
   </a>
</form>
{% endblock %}

src/templates/options_page/update_options.html
{% extends 'adminlte/index.html' %} {% load static %}
<link rel="stylesheet" type="text/css" href=" {% static " css/style.css " %}"> {% block content %}
<div class="box" style="padding: 10px">
    <div style="margin-left: 3%">
        <h3><b>Создание Options</b></h3></div>
    <div class="row">
        <div class="col-sm-5">
            <div class="card">

                <div class="card-body">

                    <form method="post">{% csrf_token %}

                        <div class="box-body" style="margin-left: 5%">
                            <div class="form-group">
                                <label for="title">Название Options</label>
                                {{ form.name }}
                            </div>
                            <div class="form-group">
                                <label for="title">Значение Options</label>
                                <span style="margin-left: 1%">{{ form.value }}</span>
                            </div>
                            {% if form.errors %}
                            <!-- Error messaging -->
                            <div id="errors">
                                <div class="inner">
                                    <p>There were some errors in the information you entered. Please correct the following:</p>
                                    {{ form.non_field_errors }}
                                    <ul>
                                        {% for field in form %} {% if field.errors %}
                                        <li>{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %} {% endfor %}
                                    </ul>
                                </div>
                            </div>
                            <!-- /Error messaging -->
                            {% endif %}
                        </div>
                        <button style="margin-left: 7%" type="submit" class="btn btn-primary">Обновить</button>
                        <a href="{% url 'pushes:options_delete' object.pk %}">
                            <button type="button" class="btn btn-danger" style="width:15%">Удалить</button>
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
</div>
<!-- /.box -->
{% endblock %} {% block body_tail %} {% endblock %}